### ISSUE TITLE
WHO Alignment issue

### ISSUE THREAD

**Issue by Eckspert** [pennmush/pennmush#1197] opened 2018-06-11 02:52 UTC
The issue here is two part, the fixed column width for cmds. When the command value reaches 5 digits, it pushes everything to the right of it out of alignment. This column needs to ether be converted to a dynamic width, or the cmd  value needs converted to something that will fit in the 4 character width.

The second issue is... The Des(criptor) column is being used to depict the connect as using SSL by appending S to the right of the descriptor, This column was never adjusted to handle this flag... thus everyone connected using SSL, inadvertently pushes their host information out of alignment.

Both these issues can be resolved by  converting to dynamic width.

**Comment by Eckspert** [comment] 2018-06-11 03:04
From Ashen-Shugar:

In bsd.c in do_who_admin you'll see this:

  notify_format(player, "%-16s %6s %9s %5s %5s %-4s %-s", T("Player Name"),
                T("Loc #"), T("On For"), T("Idle"), T("Cmds"), T("Des"),
                T("Host"));

Change the format string into an actual variable.

Something like: sprintf(format_string, "%%-%ds %%%ds %%%ds %%%ds %%%ds %%-%ds %%-s", i_loc, i_onfor, i_idle, i_cmds, i_des i_host);

Then you call:
  notify_format(player, format_string, T("Player Name"),
                T("Loc #"), T("On For"), T("Idle"), T("Cmds"), T("Des"),
                T("Host"));


Poof, dynamically declared variables.  Just have config params or whatever for the i_<values>

**Comment by talvo** [comment] 2018-06-11 08:45
Duplicate of #763.

**Closed by talvo** 2018-06-11 08:45 UTC
