### ISSUE TITLE
Monikers in WHO on connect screen

### ISSUE THREAD

**Issue by yetibeard** [pennmush/pennmush#1289] opened 2019-03-07 06:37 UTC
PennMUSH 1.8.8p0 (March 4th, 2019)

@config monikers = alltypes everywhere

Getting some weird issue when typing WHO on the connect screen. Any name that has been monikered is getting cut off and showing random bits of code and text from other places on the mush. Some of the bits seem to change every time I type WHO, others seem to stay consistent. This only happens on the connect screen, WHO works perfectly normal in-game. There is no customize WHO on the game. I've tried this on several other dbs with different code, using the same pennmush version and they all seem to do it.

Here's a screenshot comparing 'alltypes everywhere' output (left) and 'alltypes !who everywhere' output (right). https://imgur.com/a/VdREuLF

**Comment by grapenut** [comment] 2019-03-07 21:33
I tested this and found the same. Just to clarify, when you have ```@config/set monikers = alltypes everywhere``` the output of WHO looks like it should when you are logged in. It's only from the connect screen when the WHO output breaks. 

After investigating the 4 different places where WHO code is duplicated, I found a difference in the format strings between dump_users() for connect screens and do_who_* for logged in players. The problem is that dump_users() uses a fixed printf format "%16.16s" for the possibly ansified string which is likely no longer 16 characters anymore. Changing the format to just "%s" fixes the issue. The fixed width format should be unnecessary since we are manually filling using safe_fill() above.

**Comment by grapenut** [comment] 2019-03-07 21:40
![screen shot 2019-03-07 at 3 36 38 pm](https://user-images.githubusercontent.com/7102498/53990852-d915f600-40ee-11e9-8a59-be778e0ebfb9.png)
WHO output from the connect screen from before and after a ```@shutdown/reboot``` when changing the format in dump_users() from "%16.16s" to "%s".

**Comment by mike347** [comment] 2019-03-11 13:52
Fixed by grapenut's PR.

**Closed by mike347** 2019-03-11 13:52 UTC
