### ISSUE TITLE
Server crash due checking value of unset variables

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1315] opened 2019-11-01 13:22 UTC
Please remove checking values of variables with are unset (don't have a value assigned) and aren't required to run a minimal instance of Pennmush.

Actually Pennmush is crashing on variables with aren't either set or propperly described when it comes for the valuses (like for example _http_handler_).

When I try to startup Pennmush server, I recieve following output in the console:

> $ ./mush
>
> WARNING: Called without a config file argument. Assuming mush.cnf
> [truncated]:~/mush/mush-bin$ [2019-11-01 14:14:23] Seeded RNG with getentropy()
> Attempt to write to error log before it was started!
> [2019-11-01 14:14:23] CONFIG: directive 'active_queue_chunk' in cnf file ignored.
> [2019-11-01 14:14:23] CONFIG: directive '127.0.0.1' in cnf file ignored.
> Redirecting stdout and stderr to log/netmush.log`

and in the netmush.log:

> START OF LOG.
> [2019-11-01 14:05:50] CONFIG: directive 'http_handler' missing from cnf file, using default value.
> [2019-11-01 14:05:50] 1.8.7
> [2019-11-01 14:05:50] MUSH restarted, PID 26167, at Fri Nov 01 14:05:49 2019
> [2019-11-01 14:05:50] Setting ctype locale to pl_PL.UTF-8
> [2019-11-01 14:05:50] Setting time locale to pl_PL.UTF-8
> [2019-11-01 14:05:50] Setting messages locale to pl_PL.UTF-8
> [2019-11-01 14:05:50] Setting collate locale to pl_PL.UTF-8
> [ 2019-11-01 14:05:50] Listening on socket file data/netmush.sock (fd 15)
> [2019-11-01 14:05:50] Unable to open data/in.db: No such file or directory
>
> [2019-11-01 14:05:50] Couldn't open data/in.db! Creating minimal world.
> [2019-11-01 14:05:50] Reading access.cnf
> [2019-11-01 14:05:50] Reading main config file mush.cnf
> [2019-11-01 14:05:50] Reading config file alias.cnf included from mush.cnf
> [2019-11-01 14:05:50] Reading config file restrict.cnf included from mush.cnf
> [2019-11-01 14:05:50] Reading config file access.cnf included from mush.cnf
> [2019-11-01 14:05:50] map_file: unable to open file '': No such file or directory
> [2019-11-01 14:05:50] Spawning info slave, communicating using socketpair, pid 26168.
> [2019-11-01 14:05:50] Another process (Possibly another copy of this mush?) appears to be using > port 4201. Aborting.
> [2019-11-01 14:05:50] info_slave: starting event loop using epoll

before the server crashes. 

**NOTE**: There is nothing using the port 4201

Please help

**Comment by talvo** [comment] 2019-11-01 19:34
Do you have a stack trace or similar to show what/where the error is?

**Comment by mike347** [comment] 2019-11-01 19:47
I mean, not sure if this is related, but shouldn't you be using the game/restart, instead of calling the mush executable directly?

**Comment by mdziczkowski** [comment] 2019-11-01 19:49
Unfortunatelly, for now I have only what I had send

**Comment by talvo** [comment] 2019-11-01 19:54
I can't see anything to indicate a cause of the crash in what you sent; the only reference to what you're claiming is the cause is a log message which is informing you the lack of the http_handler option is being handled gracefully by defaulting it to something useful...

In fact, looking at the end of the logfile, it plainly tells you it's **not** crashing, but closing down gracefully because the port you're trying to use is in use. 

> [2019-11-01 14:05:50] Another process (Possibly another copy of this mush?) appears to be using > port 4201. Aborting.

So either your port of choice is in use by another process, or your MUSH is already running. Check ps to see which processes are running, and if the MUSH is, either kill the process, or connect and shut it down. (If not, pick a new port that isn't in use.) And then restart the MUSH - as @mike347 said, using the restart script as per the documentation.

**Comment by mdziczkowski** [comment] 2019-11-01 19:58
> I mean, not sure if this is related, but shouldn't you be using the game/restart, instead of calling the mush executable directly?

after doing some small fixes I got able (with some errors) to make the server working

@talvo I had checked multiple times thru ps and nestat and there was no other MUSH instance and nothing was running on this port

**Comment by mike347** [comment] 2019-11-11 16:46
This seems related to your other issue  and not a crash bug or related to checking of unset config variables. Closing.

**Closed by mike347** 2019-11-11 16:46 UTC
