### ISSUE TITLE
Pennmush absolute path issues

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1316] opened 2019-11-01 20:07 UTC
While testing Pennmush (sources and after compiling), I had discovered that there is a strange problem with interpreting of the absolute path in Pennmush while compiling and after it.

To resolve this issue, I suggest to use relative path instead of absolute one while compiling the files inside of the main sources folder of the Pennmush and use the absolute path only when refering to the system folders (outside the sources)

**Comment by talvo** [comment] 2019-11-01 20:10
Can you be more specific? Where have you found absolute paths that you're having an issue with?

**Comment by mdziczkowski** [comment] 2019-11-01 20:26
The problem exist mainly with the compilation, the restart and compose.sh scripts. Bellow I send you the parts of the output of the restart script with truncated (from security reason) path problems:

> $ ./restart
>
> Running from /home/[truncated]/mush/mush-bin
> Building text file indexes.
> sh ./compose.sh index 
> Building master file for /home/[truncated]/mush/mush-bin/txt/index
> ./compose.sh: 39: ./compose.sh: cannot create ..//home/[truncated]/mush/mush-bin/txt/index.txt: 
> Directory nonexistent
> Done.
> Remember to use @readcache if the mush is currently running.
> sh ./compose.sh rules 
> Building master file for /home/[truncated]/mush/mush-bin/txt/rules
> ./compose.sh: 39: ./compose.sh: cannot create ..//home/[truncated]/mush/mush-bin/txt/rules.txt: 
> Directory nonexistent
> Done.
> Remember to use @readcache if the mush is currently running.
> sh ./compose.sh hlp
> Building master file for /home/[truncated]/mush/mush-bin/txt/hlp
> ./compose.sh: 39: ./compose.sh: cannot create ..//home/[truncated]/mush/mush-bin/txt/hlp.txt: 
> Directory nonexistent
> Done.
> Remember to use @readcache if the mush is currently running.
> sh ./compose.sh nws 
> Building master file for /home/[truncated]/mush/mush-bin/txt/nws
> ./compose.sh: 39: ./compose.sh: cannot create ..//home/[truncated]/mush/mush-bin/txt/nws.txt: 
> Directory nonexistent
> Done.
> Remember to use @readcache if the mush is currently running.
> sh ./compose.sh evt 
> Building master file for /home/[truncated]/mush/mush-bin/txt/evt
> ./compose.sh: 39: ./compose.sh: cannot create ..//home/[truncated]/mush/mush-bin/txt/evt.txt: > Directory nonexistent
> Done.
> Remember to use @readcache if the mush is currently running.
> Restarting Mush.
> No data/out.db found.
> Using data/in.db.
> [2019-11-01 20:55:56] Seeded RNG with getentropy()
> [truncated]:~/mush/mush-bin$ Attempt to write to error log before it was started!
> Redirecting stdout and stderr to log/netmush.log

It look like a coding error that it searches the *.txt files in the main folder instead of the txt sub-folder

**Comment by talvo** [comment] 2019-11-01 20:54
There are no absolute paths in any of the files involved, and when I run the restart script I don't see any absolute paths in the output. As you mentioned in your previous ticket that you'd changed some things, I can't help but wonder if that may be the cause of the issue. Do you see the same behaviour with an unmodified installation? What operating system are you running on?

**Comment by mdziczkowski** [comment] 2019-11-01 22:07
@talvo the path /home/[trunchated_usernname]/mush/mush-src is absolute, plus I wasn't able to use the params: _--prefix=[path_in_above_folder]_ in config and _DESTDIR=[path_in_above_folder]_ in make without errors. The only modification I had made to solve it was declaring a variable with path of the  parent folder from the sources and had used it with above parameters

**Comment by mike347** [comment] 2019-11-01 23:01
mush/mush-bin is not the standard folder tree. The txt files should be in (pennmush)/game/txt, for example.

Git clone, run configure, run make update;make install.. run ./restart in pennmush/game and it should startup without issue.

**Comment by mdziczkowski** [comment] 2019-11-02 11:24
let me explain. I wanted that the new instance of compiled Pennmush would be in other location then the sources are, to separate one from the other one to prevent chaos in files and accidentally changing or removing the orginal sources. I think this should be taken in consider to make it possible without any problem

**Comment by talvo** [comment] 2019-11-02 17:54
My guess is that you've supplied an absolute path to something yourself?

**Comment by mdziczkowski** [comment] 2019-11-03 13:57
as I had mentioned in one of the the earlier answers, I had created a variable $mush_root containing the absolute path to the folder containing the sources and target folders (respectively "mush-src" and "mush-bin") and had used it while compilation process, with following command order:

1. `export mush_root=<absolute path to the folder containing "mush-src" and "mush-bin">`
2. `./configure --prefix=$mush_root/mush-bin`
3. `make`
4. `make install DESTDIR=$mush_root/mush-bin`

**Comment by talvo** [comment] 2019-11-04 07:29
The scripts could probably be made more robust so they can handle absolute paths, but due to this being an extremely uncommon edgecase and limited developer time, I would imagine this is unlikely to be altered in the near future. In the meantime, I'd suggest using relative paths instead of absolute to resolve your issue.

**Comment by mdziczkowski** [comment] 2019-11-04 21:50
and here lies the problem. When I tryed to use relative patches while the compilation process, I had recieved every time that absolute patches are required to continue

**Comment by talvo** [comment] 2019-11-04 22:04
Try using a relative path for make install.

**Comment by mdziczkowski** [comment] 2019-11-04 22:49
please read my previous reply carefully. I wrote there that I had already tryed it

**Comment by talvo** [comment] 2019-11-05 06:35
Please read mine; try using an absolute path for configure and a relative one for make install.

**Comment by mike347** [comment] 2020-04-22 03:21
No comments in nearly 6 months, and this being an edge case this is likely a 'Wontfix' thing. Re-open if you need to, but closing for now.

**Closed by mike347** 2020-04-22 03:21 UTC
