### ISSUE TITLE
List Functions returning Incomplete Elements

### ISSUE THREAD

**Issue by HarryCordewener** [pennmush/pennmush#1001] opened 2015-05-08 03:53 UTC
I can't find the old issue for this, so I will write up a new one. There are various list functions, such as lnum(), that should be able to 'figure out' that the string they are trying to write to a list will no longer 'fit' in the buffer. These strings should thus not be written. This is to prevent errors like lnum(high integer) returning a '1' as its last element and possibly creating code errors. 

There are other function candidates here as well, such as lsearch().

**Comment by HarryCordewener** [comment] 2015-05-08 03:55
P.S. It'd be amazing if there was a way for these list functions to 'report' in some kind of Q-Reg or something that there was more to return that they did not return... some kind of error code.

**Comment by talvo** [comment] 2015-05-08 03:57
Duplicate of #587

**Closed by talvo** 2015-05-08 03:57 UTC
