### ISSUE TITLE
Some Powers Are Not Working

### ISSUE THREAD

**Issue by ArielSchnee** [pennmush/pennmush#1337] opened 2020-07-03 12:44 UTC
When I type out 'help powers2', I get this.

```

POWERS2
  no_pay *              Doesn't need money for anything
  no_quota *            Has an unlimited quota
  open_anywhere         Can @open an exit from any room.
  pemit_all             Can @pemit to HAVEN/ulocked players.
  pick_dbref            Can recycle specific garbage dbrefs when creating objects.
  player_create         Can use @pcreate command.
  poll                  Can use @poll command.
  queue                 Has queue limit equal to the size of the database.
  quotas                Can use @quota commands on other players.
  search                Can do @search, @stats, and @entrances on anything.
  see_all               Sees everything as if it were Visual.
  see_queue             Can do @ps on anyone, and @ps/all.
  send_oob              Can use oob(), and the xch_cmd and send pueblo tags
  sql_ok                Can perform SQL queries
  tport_anything        Can @teleport anything.
  tport_anywhere        Can @teleport to anywhere.
  can_spoof             Can use @ns*emit, ns*emit() and @*emit/spoof
  can_dark              Can @set themselves dark
  can_http              Can use @http
  html                  Can use html() without restriction.
  
  * When these powers are set on a player, all the objects they own which are not set MISTRUST are also considered to have the power.

See also: help @power, and especially @power/list

```

When I tried to @power the 'can_dark', and 'html', I got these messages.

{ can_dark - I don't recognize that power. Did you mean 'CAN_DARK'? } { html - I don't recognize that power. }

Just thought I'd let you know this.

**Comment by talvo** [comment] 2020-07-03 18:49
Seems to be working fine for me. Can you show exactly what you were typing?

**Comment by talvo** [comment] 2020-07-12 13:14
Closing as can't reproduce and no follow-up - if you're still seeing this on a recent copy of Penn, please comment/reopen. Thanks.

**Closed by talvo** 2020-07-12 13:14 UTC
